version: "3.9"
services:
  db:
    image: postgres:15
    container_name: notebook_db
    environment:
      POSTGRES_USER: notebook
      POSTGRES_PASSWORD: notebook
      POSTGRES_DB: notebook_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: notebook_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:

