version: "3.9"

services:
  db:
    image: postgres:15
    container_name: notebook_db
    environment:
      POSTGRES_USER: notebook
      POSTGRES_PASSWORD: notebook
      POSTGRES_DB: notebook_dev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
